controller_list:
  - name: fake_sia5_controller
    joints:
      - robot1_joint_s
      - robot1_joint_l
      - robot1_joint_e
      - robot1_joint_u
      - robot1_joint_r
      - robot1_joint_b
      - robot1_joint_t
  - name: fake_ur5_controller
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
  - name: fake_dual_manipulator_controller
    joints:
      - robot1_joint_s
      - robot1_joint_l
      - robot1_joint_e
      - robot1_joint_u
      - robot1_joint_r
      - robot1_joint_b
      - robot1_joint_t
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint