controller_list:
  - name: fake_first_manipulator_controller
    joints:
      - robot1_joint_s
      - robot1_joint_l
      - robot1_joint_e
      - robot1_joint_u
      - robot1_joint_r
      - robot1_joint_b
      - robot1_joint_t
  - name: fake_second_manipulator_controller
    joints:
      - robot2_joint_s
      - robot2_joint_l
      - robot2_joint_e
      - robot2_joint_u
      - robot2_joint_r
      - robot2_joint_b
      - robot2_joint_t
  - name: fake_dual_manipulator_controller
    joints:
      - robot1_joint_s
      - robot1_joint_l
      - robot1_joint_e
      - robot1_joint_u
      - robot1_joint_r
      - robot1_joint_b
      - robot1_joint_t
      - robot2_joint_s
      - robot2_joint_l
      - robot2_joint_e
      - robot2_joint_u
      - robot2_joint_r
      - robot2_joint_b
      - robot2_joint_t